# [[plugins]]
# repo = 'Shougo/ddc-ui-native'
# on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/pum.vim'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-around'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_event = 'InsertEnter'
[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_event = 'InsertEnter'

# [[plugins]]
# repo = 'Shougo/ddc-source-cmdline'
# on_event = 'InsertEnter'
# [[plugins]]
# repo = 'Shougo/ddc-source-cmdline-history'
# on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hooks_file = '$TOML_DIR/hooks_file/ddc.vim'

